
title: "Aditya Acharya"
description: "My awesome website created by myself"
baseurl: ""
url: "https://aacharyaaaditya.github.io"

#Build settings
theme:

# Build settings
markdown: kramdown
theme: minima # default Jekyll theme, change if you want
plugins: [] # add plugins if needed

# Author info (custom variable example)
author:
  name: Your Name
  email: your.email@example.com

# Exclude from build
exclude:
  - README.md
  - node_modules
  
